In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_csv('Student_Marks.csv')
data.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [ ]:
data.describe()

       number_courses  time_study       Marks
count      100.000000  100.000000  100.000000
mean         5.290000    4.077140   24.417690
std          1.799523    2.372914   14.326199
min          3.000000    0.096000    5.609000
25%          4.000000    2.058500   12.633000
50%          5.000000    4.022000   20.059500
75%          7.000000    6.179250   36.676250
max          8.000000    7.957000   55.299000

In [ ]:
data.shape

(100, 3)

In [ ]:

avg_time_study = data['time_study'].mean()
print(avg_time_study)

4.07714

In [ ]:
num1=data['number_courses'].unique()
cnt = len(num1)
print(cnt)
print(num1)

def demand(number_courses):
  temp = data[(data)]